"""Change last updated field

Revision ID: 9639bd3020ca
Revises: 4e59edd0d485
Create Date: 2024-05-19 01:12:15.550291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9639bd3020ca'
down_revision: Union[str, None] = '4e59edd0d485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('last_updated', sa.Integer(), nullable=False))
    op.drop_column('player', 'resources_last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('resources_last_updated', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('player', 'last_updated')
    # ### end Alembic commands ###
