"""test if there is any changes

Revision ID: 9f193c2c0f42
Revises: 
Create Date: 2024-05-20 16:10:34.729679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f193c2c0f42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'resources_last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('resources_last_updated', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
